### ISSUE TITLE
Firefox: solar dash doesn't load properly

### ISSUE THREAD

**Issue by michaelieti** [schoolgendev/sg-dashboard#4]

**Comment by michaelieti** [comment]
Seems to be working fine on my end? @Schoolgen could you comment with the firefox version used (either here or that other issue with the maps)
![capture - firefox 52 0 2](https://cloud.githubusercontent.com/assets/11637317/24823077/ce66ce44-1c4e-11e7-8f79-bf3e92c731f8.JPG)

**Comment by Schoolgen** [comment]
Updated Firefox to latest version 52 and now works correctly.
